# Generated by Django 3.0.1 on 2020-02-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=30)),
                ('m_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('referral', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_date', models.DateField()),
                ('pid', models.IntegerField()),
                ('uid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('address', models.CharField(max_length=120)),
                ('payment_mode', models.CharField(max_length=20)),
                ('pid', models.IntegerField()),
                ('productType', models.CharField(max_length=10)),
                ('productsize', models.IntegerField()),
                ('productColour', models.CharField(max_length=20)),
                ('vendor_id', models.IntegerField()),
                ('total_amount', models.IntegerField()),
                ('status', models.CharField(max_length=25)),
                ('shipper_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=20)),
                ('sub_category', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=10)),
                ('material', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('image', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('cid', models.IntegerField()),
                ('review', models.CharField(max_length=500)),
                ('product_rating', models.IntegerField()),
                ('vendor_rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductReviewImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.IntegerField()),
                ('image', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('uid', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('size', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=30)),
                ('owner_fname', models.CharField(max_length=30)),
                ('owner_lname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('mobile', models.BigIntegerField()),
                ('email', models.TextField(max_length=50)),
                ('utype', models.CharField(max_length=20)),
                ('business_address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
                ('zone', models.CharField(max_length=30)),
                ('gst_no', models.CharField(max_length=15)),
                ('aadhar_no', models.IntegerField()),
                ('tradelicense_id', models.IntegerField()),
                ('permit_document', models.BooleanField()),
                ('address_proof', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('owner_fname', models.CharField(max_length=30)),
                ('owner_lname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('mobile', models.BigIntegerField()),
                ('email', models.TextField(max_length=50)),
                ('business_address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('pincode', models.IntegerField()),
                ('zone', models.CharField(max_length=30)),
                ('gst_no', models.CharField(max_length=15)),
                ('aadhar_no', models.IntegerField()),
                ('tradelicense_id', models.IntegerField()),
                ('permit_document', models.BooleanField()),
                ('address_proof', models.BooleanField()),
            ],
        ),
    ]
