# Generated by Django 3.0.1 on 2020-02-17 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TryOn', '0003_auto_20200216_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipper',
            name='address_proof',
            field=models.FileField(upload_to='media/rootakshat/MONSTER/PYTHON/TryOnProtoType/Files'),
        ),
        migrations.AlterField(
            model_name='shipper',
            name='permit_document',
            field=models.FileField(upload_to='media/rootakshat/MONSTER/PYTHON/TryOnProtoType/Files'),
        ),
        migrations.AlterField(
            model_name='shipper',
            name='request_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address_proof',
            field=models.FileField(upload_to='media/rootakshat/MONSTER/PYTHON/TryOnProtoType/Files'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='permit_document',
            field=models.FileField(upload_to='media/rootakshat/MONSTER/PYTHON/TryOnProtoType/Files'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='request_status',
            field=models.BooleanField(default=False),
        ),
    ]
