# Generated by Django 3.0.1 on 2020-02-25 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TryOn', '0006_auto_20200225_0600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartid', models.BigIntegerField()),
                ('category', models.CharField(max_length=120)),
                ('price', models.IntegerField()),
                ('imgeurl', models.CharField(max_length=250)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='pid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TryOn.Product'),
        ),
    ]
