# Generated by Django 3.0.1 on 2020-02-25 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TryOn', '0007_auto_20200225_1734'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.RemoveField(
            model_name='productimages',
            name='pid',
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
        migrations.DeleteModel(
            name='ProductReviewImage',
        ),
        migrations.DeleteModel(
            name='ProductStock',
        ),
        migrations.DeleteModel(
            name='Shipper',
        ),
        migrations.DeleteModel(
            name='Vendor',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImages',
        ),
    ]
