# Generated by Django 3.0.1 on 2020-02-25 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.BigIntegerField()),
                ('brand', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=20)),
                ('sub_category', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=10)),
                ('material', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.BigIntegerField()),
                ('cid', models.BigIntegerField()),
                ('review', models.CharField(max_length=500)),
                ('product_rating', models.BigIntegerField()),
                ('vendor_rating', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductReviewImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.BigIntegerField()),
                ('image', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.BigIntegerField()),
                ('uid', models.BigIntegerField()),
                ('color', models.CharField(max_length=20)),
                ('size', models.BigIntegerField()),
                ('quantity', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('owner_fname', models.CharField(max_length=30)),
                ('owner_lname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('mobile', models.BigIntegerField()),
                ('email', models.TextField(max_length=50)),
                ('business_address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('pincode', models.BigIntegerField()),
                ('zone', models.CharField(max_length=30)),
                ('gst_no', models.CharField(max_length=15)),
                ('aadhar_no', models.BigIntegerField()),
                ('tradelicense_id', models.BigIntegerField()),
                ('permit_document', models.FileField(upload_to='Files')),
                ('address_proof', models.FileField(upload_to='Files')),
                ('request_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=300)),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TryOnVendor.Product')),
            ],
        ),
    ]
